# Install and configure PostgreSQL client
---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ postgresql_client_dynamic_defaults }}'
    must_match: yes
  tags: [postgresql-client, always]

- block:
    - name: Register PostgreSQL apt key
      apt_key:
        url: '{{ postgresql_apt_key }}'
        state: present
      when: "ansible_pkg_mgr == 'apt'"

    - name: Install PostgreSQL apt repository
      apt_repository:
        repo: '{{ postgresql_apt_repository }}'
        filename: ansible_roles_postgresql_client
        state: present
        update_cache: yes
      when: "ansible_pkg_mgr == 'apt'"

    - name: Install PostgreSQL client packages
      package:
        name: '{{ postgresql_client_packages }}'
        state: present

    - name: Install PostgreSQL python packages
      pip:
        name: psycopg2-binary
        executable: '{{ postgresql_pip_path }}'
        state: "{{ (postgresql_psycopg2_version == 'latest')|ternary('latest', omit) }}"
        umask: '{{ postgresql_pip_umask }}'
        version: "{{ (postgresql_psycopg2_version == 'latest')|ternary(omit, postgresql_psycopg2_version) }}"
      environment: '{{ postgresql_pip_environment }}'
  become: yes
  tags: [postgresql-client, packages]
