---

- name: Install PostgreSQL client packages
  ansible.builtin.yum:
    name: '{{ postgresql_client_packages }}'
    enablerepo: '{{ postgresql_yum_enablerepo }}'
    state: present
  become: true
  tags: [postgresql-client, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

...
