---

- block:
    - name: Register PostgreSQL apt key
      ansible.builtin.apt_key:
        url: '{{ postgresql_apt_key }}'
        state: present

    - name: Install PostgreSQL apt repository
      ansible.builtin.apt_repository:
        repo: '{{ postgresql_apt_repository }}'
        filename: ansible_roles_postgresql_client
        state: present
        update_cache: true

    - name: Install PostgreSQL client packages
      ansible.builtin.package:
        name: '{{ postgresql_client_packages }}'
        state: present
  become: true
  tags: [postgresql-client, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

...
